// ---------------------------------------------------------------------------
// Terminal minigames.
//
// Three of them, one interface. Each builds its own DOM into a container and
// reports back exactly twice: onWin, or onQuit. Nothing else escapes.
//
// The design constraint that shapes all three: you are being hunted while you
// play, so every one has to be abandonable mid-way with no penalty beyond
// losing your progress, and none of them may need more than a few seconds of
// uninterrupted attention. A puzzle you cannot walk away from would just be a
// death sentence with extra steps.
// ---------------------------------------------------------------------------

const el = (tag, cls, text) => {
  const n = document.createElement(tag);
  if (cls) n.className = cls;
  if (text !== undefined) n.textContent = text;
  return n;
};

export const GAME_NAMES = {
  tiles: 'Reset the panel',
  sums: 'Clear the ledger',
  blocks: 'Match the plate',
};

/**
 * @param {'tiles'|'sums'|'blocks'} type
 * @param {HTMLElement} host emptied and filled with the game
 * @param {{title:string, onWin:Function, onQuit:Function}} opts
 * @returns {{destroy:Function}}
 */
export function startMinigame(type, host, opts) {
  host.innerHTML = '';

  const frame = el('div', 'mg');
  const head = el('div', 'mg-head');
  head.append(el('span', 'mg-title', opts.title), el('span', 'mg-name', GAME_NAMES[type] ?? ''));
  const body = el('div', 'mg-body');
  const foot = el('div', 'mg-foot');
  const status = el('span', 'mg-status', '');
  foot.append(status, el('span', 'mg-hint', 'Esc, or click away \u2014 you keep nothing but you lose nothing'));
  frame.append(head, body, foot);
  host.appendChild(frame);

  let done = false;
  const win = () => {
    if (done) return;
    done = true;
    status.textContent = 'Done.';
    frame.classList.add('mg-won');
    // Called straight away, NOT after a flourish on a timer.
    //
    // Closing the terminal has to recapture the mouse, and a browser will only
    // hand the pointer lock back inside the gesture that asked for it. Half a
    // second later that gesture has expired, the lock is refused, and the
    // player is dumped back into the room looking at the click-to-look screen
    // as if they had paused. The win animation is not worth that.
    opts.onWin();
  };

  const builders = { tiles: buildTiles, sums: buildSums, blocks: buildBlocks };
  (builders[type] ?? buildTiles)(body, status, win);

  return {
    destroy() { done = true; host.innerHTML = ''; },
    /** Called when the world pulls the player away from the screen. */
    abort() {
      if (done) return;
      done = true;
      host.innerHTML = '';
      opts.onQuit?.();
    },
  };
}

// ---------------------------------------------------------------------------
// 1. Reset the panel — 4x4, a press flips the tile and its neighbours.
//
// Generated by walking backwards from solved, so it is always solvable. Ten
// scrambling presses is enough to look chaotic and short enough to unpick.
// ---------------------------------------------------------------------------

function buildTiles(body, status, win) {
  const N = 4;
  const state = new Array(N * N).fill(false);
  const idx = (r, c) => r * N + c;

  const flip = (r, c) => {
    if (r < 0 || c < 0 || r >= N || c >= N) return;
    state[idx(r, c)] = !state[idx(r, c)];
  };
  const press = (r, c) => {
    flip(r, c); flip(r - 1, c); flip(r + 1, c); flip(r, c - 1); flip(r, c + 1);
  };

  // Six scrambling presses, not ten. Ten looks like noise and takes long enough
  // that something usually arrives before you finish.
  do {
    state.fill(false);
    for (let k = 0; k < 6; k++) press((Math.random() * N) | 0, (Math.random() * N) | 0);
  } while (state.every((v) => !v));   // never hand out an already-solved board

  const grid = el('div', 'mg-grid');
  const cells = [];
  for (let r = 0; r < N; r++) {
    for (let c = 0; c < N; c++) {
      const b = el('button', 'mg-tile');
      b.addEventListener('click', () => {
        press(r, c);
        render();
      });
      grid.appendChild(b);
      cells.push(b);
    }
  }
  body.append(
    el('p', 'mg-lead', 'Turn every light off.'),
    el('p', 'mg-sub', 'Pressing a switch flips that light AND the four touching it \u2014 up, down, left, right. There is always a way; work the top row first and let the rest follow.'),
    grid,
  );

  function render() {
    let lit = 0;
    cells.forEach((b, i) => {
      b.classList.toggle('on', state[i]);
      if (state[i]) lit++;
    });
    status.textContent = `${lit} still lit`;
    if (lit === 0) win();
  }
  render();
}

// ---------------------------------------------------------------------------
// 2. Clear the ledger — five questions, one at a time.
//
// Addition and subtraction use two two-digit numbers. Multiplication uses a
// two-digit against a single digit: 47x83 in your head while something walks
// towards you is not a puzzle, it is a formality you fail.
// ---------------------------------------------------------------------------

function buildSums(body, status, win) {
  const TOTAL = 4;
  let index = 0;

  const lead = el('p', 'mg-lead', 'Four sums. Type the answer and press Enter.');
  const sub = el('p', 'mg-sub', 'Whole numbers only, never negative. A wrong answer just shakes \u2014 nothing is lost, try again.');
  const q = el('div', 'mg-sum');
  const input = el('input', 'mg-input');
  input.type = 'text';
  input.inputMode = 'numeric';
  input.autocomplete = 'off';
  const submit = el('button', 'mg-go', 'Enter');
  const row = el('div', 'mg-sum-row');
  row.append(input, submit);
  body.append(lead, sub, q, row);

  let answer = 0;

  function ask() {
    const op = ['+', '-', '\u00d7'][(Math.random() * 3) | 0];
    let a, b;
    if (op === '\u00d7') {
      a = 10 + ((Math.random() * 90) | 0);
      b = 2 + ((Math.random() * 8) | 0);
      answer = a * b;
    } else if (op === '+') {
      a = 10 + ((Math.random() * 90) | 0);
      b = 10 + ((Math.random() * 90) | 0);
      answer = a + b;
    } else {
      a = 10 + ((Math.random() * 90) | 0);
      b = 10 + ((Math.random() * (a - 9)) | 0);   // never negative
      answer = a - b;
    }
    q.textContent = `${a} ${op} ${b}`;
    input.value = '';
    status.textContent = `${index} of ${TOTAL}`;
    input.focus();
  }

  function check() {
    if (input.value.trim() === '') return;
    if (Number(input.value.trim()) === answer) {
      index++;
      if (index >= TOTAL) { status.textContent = `${TOTAL} of ${TOTAL}`; win(); return; }
      ask();
    } else {
      input.value = '';
      q.classList.remove('shake');
      void q.offsetWidth;          // restart the animation
      q.classList.add('shake');
    }
  }

  submit.addEventListener('click', check);
  input.addEventListener('keydown', (e) => {
    e.stopPropagation();           // Escape still bubbles to the host
    if (e.key === 'Enter') check();
  });
  ask();
  setTimeout(() => input.focus(), 30);
}

// ---------------------------------------------------------------------------
// 3. Match the plate — swap blocks until the row matches the picture above it.
//
// Two clicks to swap. Nine blocks: long enough that you cannot solve it by
// accident, short enough to take in at a glance when you are already
// panicking. The row wraps on a narrow screen rather than shrinking the
// blocks below what a thumb can hit.
// ---------------------------------------------------------------------------

const BLOCK_COLOURS = [
  '#c2704a', '#4a7fc2', '#c2b04a', '#6ac28a', '#a06ac2',
  '#c24a6a', '#4ac2b4', '#c2884a', '#8ac24a',
];

function buildBlocks(body, status, win) {
  // Nine columns. BLOCK_COLOURS must have at least this many entries — every
  // block is a different colour, so the two rows can be compared at a glance.
  const N = 9;
  const target = [...Array(N).keys()];
  let current = shuffled(target);
  while (current.every((v, i) => v === target[i])) current = shuffled(target);

  const targetRow = el('div', 'mg-blocks mg-target');
  const playRow = el('div', 'mg-blocks');
  body.append(
    el('p', 'mg-lead', 'Make the bottom row match the top row.'),
    el('p', 'mg-sub', 'Click one block, then click another, and the two trade places. The counter tells you how many are already correct.'),
    targetRow, el('div', 'mg-divider'), playRow,
  );

  target.forEach((c) => {
    const b = el('div', 'mg-block');
    b.style.background = BLOCK_COLOURS[c];
    targetRow.appendChild(b);
  });

  let picked = -1;
  const cells = [];
  for (let i = 0; i < N; i++) {
    const b = el('button', 'mg-block');
    b.addEventListener('click', () => {
      if (picked === -1) { picked = i; render(); return; }
      if (picked === i) { picked = -1; render(); return; }
      [current[picked], current[i]] = [current[i], current[picked]];
      picked = -1;
      render();
    });
    playRow.appendChild(b);
    cells.push(b);
  }

  function render() {
    let right = 0;
    cells.forEach((b, i) => {
      b.style.background = BLOCK_COLOURS[current[i]];
      b.classList.toggle('picked', i === picked);
      if (current[i] === target[i]) right++;
    });
    status.textContent = `${right} of ${N} in place`;
    if (right === N) win();
  }
  render();
}

function shuffled(arr) {
  const a = arr.slice();
  for (let i = a.length - 1; i > 0; i--) {
    const j = (Math.random() * (i + 1)) | 0;
    [a[i], a[j]] = [a[j], a[i]];
  }
  return a;
}
